events/urls.py
from django.urls import path, include

from events.views import EventsListActive, EventsListProcess, EventsListClose
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsList, name='event_list'),
    path('active/', EventsListActive.as_view(), name='EventsListActive'),
    path('process/', EventsListProcess.as_view(), name='EventsListProcess'),
    path('closed/', EventsListClose.as_view(), name='EventsListClose'),
    path('<int:pk>/', views.EventDetail, name='event_detail'),
    path('<int:pk>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('<int:pk>/unfavorite/', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite/', views.profile_favorite, name='profile_favorite'),
    path('<int:pk_event>/unfollow/<int:pk_funk>', views.profile_unfollow_func, name='profile_unfollow_func'),
    path('<int:pk_event>/follow/<int:pk_funk>', views.profile_follow_func, name='profile_follow_func'),
    path('follow/', views.follow_index, name='follow_index'),
    path('favorites/', views.favorites_index, name='favorites_index'),
    path('own/', views.own_index, name='own_index'),
    path('event_create/', views.event_create, name='event_create'),
    path('<int:pk>/function_create/', views.function_create, name='function_create'),
    path('<int:pk>/event_edit/', views.event_edit, name='event_edit'),
    path('<int:pk>/function_edit/', views.function_edit, name='function_edit'),

]

live/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from live.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('events/', include('events.urls', namespace='events')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', HomeView.as_view(), name='live_index'),
    path('auth/', include('auth_users.urls', namespace='auth_users')),
    path('volunteers/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import ProjectDetail, ProjectsList
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectsList.as_view(), name='projects_list'),
    path('<int:pk>/', views.ProjectDetail, name='project_detail'),
    path('<int:pk>/unfavorite', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite', views.profile_favorite, name='profile_favorite'),
    path('<int:pk>/favorite_part', views.profile_favorite_part, name='profile_favorite_part'),

]

projects/models.py
from django.db import models
import os

from users.models import User
from live import settings


class Project(models.Model):
    def project_avatar_path(instance, filename):
        ext = filename.split('.')[-1]
        fullname = f'projects/avatars/{instance.pk}.{ext}'
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, fullname)):
            os.remove(os.path.join(settings.MEDIA_ROOT, fullname))
        return f'projects/avatars/{instance.pk}.{ext}'

    name = models.CharField(
        max_length=20,
        verbose_name='Наименование',
        db_index=True
    )
    avatar_url = models.ImageField(
        upload_to=project_avatar_path,
        verbose_name='Аватар'
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True
    )
    goal = models.TextField(
        verbose_name='Цели',
        blank=True,
        null=True
    )
    result = models.TextField(
        verbose_name='Результаты',
        blank=True,
        null=True
    )
    marker = models.TextField(
        verbose_name='Маркер',
        null=True
    )

    class Meta:
        verbose_name = 'Проекты'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.name


class UserProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

projects/views.py
from django.views.generic import DetailView, ListView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Project
from events.models import Favorites, Event
from django.contrib.auth.decorators import login_required


@login_required
def ProjectDetail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    events_project = project.events.all()
    favorites = [Favorites.objects.filter(user=request.user, event=event).exists() for event in events_project]
    len_event = len(events_project)
    if favorites.count(True)==len(favorites):
        favorites = True
    elif True in favorites and False in favorites:
        favorites = 'part'
    else:
        favorites = False
    context = {
        'project': project,
        'events_project': events_project,
        'favorites': favorites,
        'len_event': len_event
    }
    return render(request, 'projects/project_detail.html', context)


class ProjectsList(ListView):
    model = Project
    template_name = 'projects/projects.html'
    context_object_name = 'projects'


@login_required
def profile_unfavorite(request, pk):
    project = get_object_or_404(Project, pk=pk)
    events_project = project.events.all()
    for event in events_project:
        favorite = get_object_or_404(Event, pk=event.pk)
        Favorites.objects.filter(user=request.user, event=favorite).delete()
    return redirect('projects:project_detail', pk=pk)


@login_required
def profile_favorite(request, pk):
    project = get_object_or_404(Project, pk=pk)
    events_project = project.events.all()
    for event in events_project:
        favorite = get_object_or_404(Event, pk=event.pk)
        Favorites.objects.get_or_create(user=request.user, event=favorite)
    return redirect('projects:project_detail', pk=pk)


@login_required
def profile_favorite_part(request, pk):
    project = get_object_or_404(Project, pk=pk)
    events_project = project.events.all()
    # event = [event for event in events_project]
    # favorites = [Favorites.objects.filter(user=request.user, event=event).exists() for event in events_project]
    # for index in range(len(favorites)):
    #     if favorites[index] == True:
    #         favorite = event[index]
    #         Favorites.objects.filter(user=request.user, event=favorite).delete()
    for event in events_project:
        favorite = get_object_or_404(Event, pk=event.pk)
        Favorites.objects.get_or_create(user=request.user, event=favorite)
    return redirect('projects:project_detail', pk=pk)

templates/projects/project_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ project.name }}{% endblock %}
{% block content %}
<div class="limiter cl-gr">
      <div class="container-fix">
          <div class="content-c d-flex">
              <div class="content-r text-center">
                  <img src="{{ project.avatar_url.url }}" width="180" height="180">
              </div>
              <div class="content-l">
                  <h2 class="cl_h2">{{ project.name }}</h2>
                  <ul class="project_li">
                     <li>
                         {{ project.description }}
                     </li>
                  </ul>
                    {% if favorites == 'part' %}
                        <a class="link-create" href="{% url 'projects:profile_favorite_part' pk=project.pk %}">
                              Следить за всеми мероприятиями
                        </a>
                    {% elif favorites %}
                        <a class="link-favorite" href="{% url 'projects:profile_unfavorite' pk=project.pk %}">
                              <i class="fa-solid fa-star"></i><span>Из избранного</span>
                        </a>
                    {% else %}
                        <a class="link-favorite" href="{% url 'projects:profile_favorite' pk=project.pk %}">
                              <i class="fa-regular fa-star"></i><span>В избранное</span>
                        </a>
                    {% endif %}

              </div>
          </div>
          <div class="content-c">
              <div class="event-info-title">
                    <span>Основная информация</span>
              </div>
               <div class="event-info-txt">
                      <table>
                          <tr>
                              <td><img src="/static/img/goal.png" width="25" height="25">Цель проекта: </td>
                              <th>{{ project.goal }}</th>
                          </tr>
                          <tr>
                              <td><img src="/static/img/result.png" width="25" height="25">Результат проекта: </td>
                              <th>{{ project.result }}</th>
                          </tr>
                      </table>
               </div>
              <div class="event-info-title">
                    <span>Мероприятия</span>
              </div>
              <div class="event-info-txt">
                  {% if len_event > 0 %}
                  <div class="line_block">
                      <div class="line_block_container">
                        {% for project in events_project %}
                            <a href="{% url 'events:event_detail' pk=project.pk %}">
                                <div class="line_block_pr">
                                    <img src="{{ project.avatar_url.url }}" width="200" height="200"> <br>
                                    <p class="title_line_block">{{ project.name }}</p>
                                    <p class="hideText">Смотреть подробнее>></p>
                                </div>
                            </a>
                        {% endfor %}
                      </div>
                  </div>

                  {% else %}
                    Мероприятия отсутствуют
                  {% endif %}
              </div>
          </div>
      </div>
</div>

{% endblock %}

templates/projects/projects.html
{% extends "base.html" %}
{% load static %}
{% block title %}Проекты{% endblock %}
{% block content %}
    <div class="limiter">
      <div class="container-fix">
        <div class="line_block">
            <h2 class="cl_h2">Наши проекты</h2>
            <div class="line_block_container">
                {% for project in projects %}
                    <a href="{% url 'projects:project_detail' pk=project.pk %}">
                        <div class="line_block_pr">
                            <img src="{{ project.avatar_url.url }}" width="200" height="200"> <br>
                            <p class="title_line_block">{{ project.name }}</p>
                            <p class="hideText">Смотреть подробнее>></p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
      </div>
    </div>
{% endblock %}