auth_users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView
from django.urls import path

from auth_users.views import AuthView, RegistrationView, PassResetView

app_name = 'auth_users'

urlpatterns = [
    path('login/', AuthView.as_view(template_name='auth_users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(template_name='auth_users/registration.html'), name='registration'),
    path('password/reset/', PassResetView.as_view(template_name='auth_users/password_reset.html'), name='password_reset'),
]

events/urls.py
from django.urls import path, include

from events.views import EventsListActive, EventsListProcess, EventsListClose
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsList, name='event_list'),
    path('active/', EventsListActive.as_view(), name='EventsListActive'),
    path('process/', EventsListProcess.as_view(), name='EventsListProcess'),
    path('closed/', EventsListClose.as_view(), name='EventsListClose'),
    path('<int:pk>/', views.EventDetail, name='event_detail'),
    path('<int:pk>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('<int:pk>/unfavorite/', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite/', views.profile_favorite, name='profile_favorite'),
    path('<int:pk_event>/unfollow/<int:pk_funk>', views.profile_unfollow_func, name='profile_unfollow_func'),
    path('<int:pk_event>/follow/<int:pk_funk>', views.profile_follow_func, name='profile_follow_func'),
    path('follow/', views.follow_index, name='follow_index'),
    path('favorites/', views.favorites_index, name='favorites_index'),
    path('own/', views.own_index, name='own_index'),
    path('event_create/', views.event_create, name='event_create'),
    path('<int:pk>/function_create/', views.function_create, name='function_create'),
    path('<int:pk>/event_edit/', views.event_edit, name='event_edit'),
    path('<int:pk>/function_edit/', views.function_edit, name='function_edit'),

]

live/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from live.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('events/', include('events.urls', namespace='events')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', HomeView.as_view(), name='live_index'),
    path('auth/', include('auth_users.urls', namespace='auth_users')),
    path('volunteers/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import ProjectDetail, ProjectsList
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectsList.as_view(), name='projects_list'),
    path('<int:pk>/', views.ProjectDetail, name='project_detail'),
    path('<int:pk>/unfavorite', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite', views.profile_favorite, name='profile_favorite'),
    path('<int:pk>/favorite_part', views.profile_favorite_part, name='profile_favorite_part'),

]

users/urls.py
from django.urls import path

from .views import UserListView, UserDetailView, EventListView, CertificateListView, ReviewListView, UserEdit

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(template_name='users/volunteers.html'), name='volunteers'),
    path('<int:pk>/', UserDetailView.as_view(template_name='users/volunteer_detail.html'), name='volunteer_detail'),
    path('<int:pk>/events/', EventListView.as_view(template_name='users/events.html'), name='events'),
    path('<int:pk>/certificates/', CertificateListView.as_view(template_name='users/certificates.html'), name='certificates'),
    path('<int:pk>/reviews/', ReviewListView.as_view(template_name='users/reviews.html'), name='reviews'),
    path('edit/', UserEdit.as_view(template_name='users/edit.html'), name='edit'),
]

templates/includes/avatar_input.html
<div class="input-ava-container">
    <div class="input-ava-background">
        <img id="ava-img" width="180" height="180" class="input-ava-img" src="{{ widget.value.url }}" onclick='ava.click()'>
        <input id="ava" style="visibility:hidden;width:0px;" onchange="readURL(this)" type="{{ widget.type }}" name="{{ widget.name }}"{% include 'django/forms/widgets/attrs.html' %}/>
        <span class="input-ava-change" onclick='ava.click()'>Выбрать</span>
    </div>
</div>
<br/>

templates/includes/event_input.html
<div class="input-ava-container">
    <div class="input-ava-background input-ava-background-cr">
        <img id="ava-img" width="180" height="180" class="input-ava-img input-ava-img-cr" src="{% if widget.value.url %}{{widget.value.url}}{% else %}/media/events/avatars/4.png{% endif %}" onclick='ava.click()'>
        <input id="ava" style="visibility:hidden;width:0px;" onchange="readURL(this)" type="{{ widget.type }}" name="{{ widget.name }}"{% include 'django/forms/widgets/attrs.html' %}/>
        <span class="input-ava-change" onclick='ava.click()'>Выбрать</span>
    </div>
</div>
<br/>

templates/includes/footer.html
<footer class="text-center border-top">
  <div class="footer-container">
    <div class="container-fix">
      <div class="network">

      </div>
    </div>
    <p class="inglobal-bold border-top text-center py-2">Все права защищены<br>© {{ year }} Copyright <span style="color:red">ЖИ</span>ВИ</p>
  </div>
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="">
    <div class="container-fix container-header">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo.png' %}" width="40" height="30" class="d-inline-block align-top" alt="">
        <span class="title-name1 inglobal-bold">ЖИ</span><span class="title-name2 inglobal-bold">ВИ</span>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
      </a>
      <ul class="nav" id="nav">
        {% if request.user.is_authenticated %}
            <li>
                <div class="head-an">
                    <a id="about" href="{% url 'live_index' %}"><span>Главная</a>
                    <a id="event" href="{% url 'events:event_list' %}">Мероприятия</a>
                    <a id="projects" href="{% url 'projects:projects_list' %}">Проекты</a>
                </div>
            </li>

            <li class="nav-item">
                <div class="user-menu"><div class="user-menu-container" id="user-menu-container" v-on:click="openMenu">
                      <img width="35" height="35" class="user-avatar" src="{{request.user.avatar.url}}">
                      <span class="user-name">{{ request.user.first_name }}</span>
                    </div>
                    <div class="menu-user-div" :key="menuUser" v-if="menuUser">
                        <ul class="menu-user-ul">
                             <li><a class="menu-user-a menu-user-a-profile" href="{% url 'users:volunteer_detail' pk=request.user.pk %}">Профиль</a></li>
                             <li><a class="menu-user-a" href="{% url 'events:event_create' %}">Создать мероприятие</a></li>
                             <li><a class="menu-user-a menu-user-a-exit" href="{% url 'auth_users:logout' %}">Выйти</a></li>
                        </ul>
                    </div>
                </div>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link link-light inglobal-bold" href="{% url 'auth_users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light inglobal-bold" href="{% url 'auth_users:registration' %}">Регистрация</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item-n active">
                        <span class="page-link-n">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item-n">
                        <a class="page-link-n" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endif %}

templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="container-nav">
    <ul class="tabs-nav">
      <li>
        <a
          class="link-nav {% if '/' == request.path %}link-nav-active{% endif %}"
          href="{% url 'live_index' %}"
        >
          Ближайшие мероприятия
        </a>
      </li>
      <li>
        <a
          class="link-nav {% if '/events/favorites/' == request.path %}link-nav-active{% endif %}"
          href="{% url 'events:favorites_index' %}"
        >
          Избранные мероприятия
        </a>
      </li>
      <li>
        <a
           class="link-nav {% if '/events/follow/' == request.path %}link-nav-active{% endif %}"
           href="{% url 'events:follow_index' %}"
        >
          Принимаю участие
        </a>
      </li>
      <li>
        <a
           class="link-nav {% if '/events/own/' == request.path %}link-nav-active{% endif %}"
           href="{% url 'events:own_index' %}"
        >
          Созданные мной
        </a>
      </li>
    </ul>
  </div>
{% endif %}

templates/includes/switcher_status_events.html
{% if user.is_authenticated %}
  <div class="container-nav">
    <ul class="tabs-nav">
      <li>
        <a
          class="link-nav {% if '/events/' == request.path %}link-nav-active{% endif %}"
          href="{% url 'events:event_list' %}"
        >
          Все
        </a>
      </li>
      <li>
        <a
          class="link-nav {% if '/events/active/' == request.path %}link-nav-active{% endif %}"
          href="{% url 'events:EventsListActive' %}"
        >
          Активные
        </a>
      </li>
      <li>
        <a
          class="link-nav {% if '/events/process/' == request.path %}link-nav-active{% endif %}"
          href="{% url 'events:EventsListProcess' %}"
        >
          Волонтеры набраны
        </a>
      </li>
      <li>
        <a
           class="link-nav {% if '/events/closed/' == request.path %}link-nav-active{% endif %}"
           href="{% url 'events:EventsListClose' %}"
        >
          Закрытые
        </a>
      </li>
    </ul>
  </div>
{% endif %}