events/urls.py
from django.urls import path, include

from events.views import EventsListActive, EventsListProcess, EventsListClose
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsList, name='event_list'),
    path('active/', EventsListActive.as_view(), name='EventsListActive'),
    path('process/', EventsListProcess.as_view(), name='EventsListProcess'),
    path('closed/', EventsListClose.as_view(), name='EventsListClose'),
    path('<int:pk>/', views.EventDetail, name='event_detail'),
    path('<int:pk>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('<int:pk>/unfavorite/', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite/', views.profile_favorite, name='profile_favorite'),
    path('<int:pk_event>/unfollow/<int:pk_funk>', views.profile_unfollow_func, name='profile_unfollow_func'),
    path('<int:pk_event>/follow/<int:pk_funk>', views.profile_follow_func, name='profile_follow_func'),
    path('follow/', views.follow_index, name='follow_index'),
    path('favorites/', views.favorites_index, name='favorites_index'),
    path('own/', views.own_index, name='own_index'),
    path('event_create/', views.event_create, name='event_create'),
    path('<int:pk>/function_create/', views.function_create, name='function_create'),
    path('<int:pk>/event_edit/', views.event_edit, name='event_edit'),
    path('<int:pk>/function_edit/', views.function_edit, name='function_edit'),

]

live/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from live.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('events/', include('events.urls', namespace='events')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', HomeView.as_view(), name='live_index'),
    path('auth/', include('auth_users.urls', namespace='auth_users')),
    path('volunteers/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import ProjectDetail, ProjectsList
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectsList.as_view(), name='projects_list'),
    path('<int:pk>/', views.ProjectDetail, name='project_detail'),
    path('<int:pk>/unfavorite', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite', views.profile_favorite, name='profile_favorite'),
    path('<int:pk>/favorite_part', views.profile_favorite_part, name='profile_favorite_part'),

]

users/urls.py
from django.urls import path

from .views import UserListView, UserDetailView, EventListView, CertificateListView, ReviewListView, UserEdit

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(template_name='users/volunteers.html'), name='volunteers'),
    path('<int:pk>/', UserDetailView.as_view(template_name='users/volunteer_detail.html'), name='volunteer_detail'),
    path('<int:pk>/events/', EventListView.as_view(template_name='users/events.html'), name='events'),
    path('<int:pk>/certificates/', CertificateListView.as_view(template_name='users/certificates.html'), name='certificates'),
    path('<int:pk>/reviews/', ReviewListView.as_view(template_name='users/reviews.html'), name='reviews'),
    path('edit/', UserEdit.as_view(template_name='users/edit.html'), name='edit'),
]

events/forms.py
from django.forms import ModelForm, DateField, modelformset_factory
from django import forms
from .models import Follow, Function, Event
from datetime import datetime
from django.forms.widgets import ClearableFileInput, DateTimeInput


class EventForm(ModelForm):
    class Meta:
        model = Follow
        fields = ('function',)

    def __init__(self, *args, **kwargs):
        if 'event' in kwargs and kwargs['event'] is not None:
            event = kwargs.pop('event')
            qs = Function.objects.filter(event_id=event.pk)
            total_pk = []
            for qs_one in qs:
                if qs_one.count > qs_one.following.count():
                    total_pk.append(qs_one.pk)
            qs = qs.filter(pk__in=total_pk)
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['function'].queryset = qs


class EventInput(ClearableFileInput):
    template_name = "includes/event_input.html"


class EventFormCreate(ModelForm):
    date_start = forms.DateTimeField(
        label='Дата начала')

    date_end = forms.DateTimeField(
        label='Дата окончания')

    class Meta:
        model = Event
        fields = ('coordinates_latitude', 'coordinates_longitude', 'address', 'avatar_url', 'name', 'status', 'description', 'date_start', 'date_end', 'project')
        widgets = {
            'avatar_url': EventInput
        }


class FunctionFormCreate(ModelForm):
    class Meta:
        model = Function
        fields = ('name', 'description', 'task', 'condition', 'count')

events/views.py
import json

from django.views.generic import DetailView, ListView
from django.shortcuts import redirect, get_object_or_404, render, reverse
from datetime import datetime

from .models import Event, Follow, Function, Favorites
from .filters import Event_Filter
from .forms import EventForm, EventFormCreate, FunctionFormCreate
from django.contrib.auth.decorators import login_required

from rest_framework import serializers
from rest_framework.renderers import JSONRenderer

from events.models import Event
from users.models import User
from projects.models import Project


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('pk', 'avatar', 'first_name', 'last_name')


class ProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = ('pk', 'name', 'marker')


class EventSerializer(serializers.ModelSerializer):
    contact_user = UserSerializer(read_only=True)
    project = ProjectSerializer(read_only=True)

    class Meta:
        model = Event
        fields = ('pk', 'name', 'date_end', 'date_start', 'coordinates_latitude', 'coordinates_longitude', 'address', 'project', 'contact_user')


@login_required
def EventDetail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    following = Follow.objects.filter(user=request.user, event=event).exists()
    favorites = Favorites.objects.filter(user=request.user, event=event).exists()
    following_func = []
    for i in Follow.objects.filter(user=request.user, event=event):
        following_func.append(i.function.pk)
    functions = Function.objects.filter(event=event)
    len_functions = len(functions)
    user_count = event.following.count()
    users_following = Follow.objects.filter(event=event)
    count_u=[]
    for i in functions:
        count_u.append(int(i.count))
    count_remainder = (True if (sum(count_u)>user_count) else False)
    count_u_func={}
    for i in functions:
        count_u_func[i.pk] = i.following.count()
    form = EventForm(request.POST or None, event=event)
    if form.is_valid():
        fun = form.save(commit=False)
        fun.user = request.user
        fun.event = event
        fun.save()
        return redirect('events:event_detail', pk=pk)
    context = {
        'event': event,
        'following': following,
        'functions': functions,
        'user_count': user_count,
        'favorites': favorites,
        'users_following': users_following,
        'len_functions': len_functions,
        'count_remainder': count_remainder,
        'following_func': following_func,
        'count_u_func': count_u_func,
        'form': form
    }
    return render(request, 'events/event_detail.html', context)


def EventsList(request):
    events = Event.objects.all()
    filter = Event_Filter(request.GET, queryset=events)
    events = filter.qs
    context = {'events': events, 'filter': filter}
    return render(request, 'events/events.html', context)


class EventsListActive(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            functions=Function.objects.filter(event=event_one)
            count_u = []
            for i in functions:
                count_u.append(int(i.count))
            if sum(count_u)>event_one.following.count() and event_one.date_end.date()>datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


class EventsListProcess(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            functions=Function.objects.filter(event=event_one)
            count_u = []
            for i in functions:
                count_u.append(int(i.count))
            if sum(count_u)==event_one.following.count() and event_one.date_end.date()>datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


class EventsListClose(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            if event_one.date_end.date()<datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


@login_required
def profile_unfollow(request, pk):
    follow = get_object_or_404(Event, pk=pk)
    Follow.objects.filter(user=request.user, event=follow).delete()
    return redirect('events:event_detail', pk=pk)


@login_required
def follow_index(request):
    follows = Event.objects.filter(following__user=request.user)
    serializer = EventSerializer(follows, many=True)
    context = {
        'follows': follows,
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'condition': True
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def profile_unfavorite(request, pk):
    favorite = get_object_or_404(Event, pk=pk)
    Favorites.objects.filter(user=request.user, event=favorite).delete()
    return redirect('events:event_detail', pk=pk)


@login_required
def profile_favorite(request, pk):
    favorite = get_object_or_404(Event, pk=pk)
    Favorites.objects.get_or_create(user=request.user, event=favorite)
    return redirect('events:event_detail', pk=pk)


@login_required
def profile_unfollow_func(request, pk_event, pk_funk):
    event_follow = get_object_or_404(Event, pk=pk_event)
    func_follow = get_object_or_404(Function, event_id=event_follow.pk, pk=pk_funk)
    Follow.objects.filter(user=request.user, event=event_follow, function=func_follow).delete()
    return redirect('events:event_detail', pk=event_follow.pk)

@login_required
def profile_follow_func(request, pk_event, pk_funk):
    event_follow = get_object_or_404(Event, pk=pk_event)
    func_follow = get_object_or_404(Function, event_id=event_follow.pk,pk=pk_funk)
    Follow.objects.get_or_create(user=request.user, event=event_follow, function=func_follow)
    return redirect('events:event_detail', pk=event_follow.pk)


@login_required
def favorites_index(request):
    favorites = Event.objects.filter(favorites__user=request.user)
    serializer = EventSerializer(favorites, many=True)
    context = {
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'follows': favorites,
        'condition': True
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def own_index(request):
    owns = Event.objects.filter(contact_user=request.user)
    serializer = EventSerializer(owns, many=True)
    context = {
        'owns': owns,
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'condition': False
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def event_create(request):
    form = EventFormCreate(request.POST or None)
    if form.is_valid():
        event = form.save(commit=False)
        event.contact_user = request.user
        event.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_event.html', {'form': form}
    )


@login_required
def function_create(request, pk):
    form = FunctionFormCreate(request.POST or None)
    event = Event.objects.get(pk=pk)
    if form.is_valid():
        function = form.save(commit=False)
        function.event = event
        function.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_function.html', {'form': form}
    )


@login_required
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.user != event.contact_user:
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    form = EventFormCreate(
        request.POST or None,
        files=request.FILES or None,
        instance=event
    )
    if form.is_valid():
        form.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_event.html', {'form': form}
    )


@login_required
def function_edit(request, pk):
    function = get_object_or_404(Function, pk=pk)
    if request.user != function.event.contact_user:
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': function.event.pk}
        ))
    form = FunctionFormCreate(
        request.POST or None,
        files=request.FILES or None,
        instance=function
    )
    if form.is_valid():
        form.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': function.event.pk}
        ))
    return render(
        request, 'events/create_function.html', {'form': form}
    )

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Avg
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView

from events.models import UserEvent, Event
from users.forms import UserEditForm
from users.models import User, ReviewUser, Certificate


class UserDetailView(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        rating = ReviewUser.objects.filter(volunteer=self.object)
        events = UserEvent.objects.filter(user=self.object)
        context['rating'] = rating.aggregate(Avg('rating'))['rating__avg']
        context['stats_review'] = rating.count()
        context['stats_event'] = events.count()

        return context


class UserListView(ListView):
    model = User


class EventListView(ListView):
    def get_queryset(self):
        events = Event.objects.filter(userevent__user=self.kwargs['pk'])
        return events


class ReviewListView(ListView):
    def get_queryset(self):
        reviews = ReviewUser.objects.filter(volunteer=self.kwargs['pk'])
        return reviews


class CertificateListView(ListView):
    def get_queryset(self):
        certificates = Certificate.objects.filter(user=self.kwargs['pk'])
        return certificates


class UserEdit(LoginRequiredMixin, UpdateView):
    form_class = UserEditForm

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.pk)

    def get_success_url(self):
        return reverse_lazy('users:volunteer_detail', kwargs={'pk': self.request.user.pk})

templates/users/certificates.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}Сертификаты волонтера{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c" id="modalCert">
                {% for certificate in user.certificates.all %}
                    <img height="100" width="160" src="{% static certificate.url %}" v-on:click="openModal('{% static certificate.url %}')">
                {% endfor %}
                <div class="modalDialog" :key="isModal" v-if="isModal">
                    <div>
                        <img height="500" width="800" :src="src" v-on:click="openModal">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/volunteer.js' %}"></script>
{% endblock %}

templates/users/edit.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}Редактировать профиль{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c">
                <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.label == 'Аватар'%}
                            {{field}}
                        {% else %}
                            <div class="mt-4 d-flex" {% if field.field.required %}
                                      aria-required="true"
                                    {% else %}
                                      aria-required="false"
                                    {% endif %}>
                                <span class="form-edit-label">{{field.label}}:</span>
                                <div>
                                    {% if field.label == 'Личная информация' %}
                                        <div class="form-edit-info-container">
                                            <div class="form-edit-info-nav">
                                                <span id="form-edit-info-b" class="blr-24"><i class="fa-solid fa-bold"></i></span>
                                                <span id="form-edit-info-p"><i class="fa-solid fa-paragraph"></i></span>
                                            </div>
                                            {{field}}
                                        </div>
                                    {% else %}
                                        {{field|add_class:'form-edit-user'}}
                                    {% endif %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <span class="form-edit-error">* {{ error|escape }}</span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <button class="btn-save" type="submit">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/volunteer_edit.js' %}"></script>
{% endblock %}

templates/users/events.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}Мероприятия волонтера{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c">
                {% for event in object_list %}
                    <a href="{% url 'events:event_detail' pk=event.pk %}">{{event.name}}</a><br>
                    {{event.status}}<br>
                    {{event.date_start}} - {{event.date_end}}<br><br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/reviews.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}Отзывы волонтера{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c">
                {% for review in object_list %}
                    <a href="{% url 'projects:project_detail' pk=review.organization.pk %}">{{review.organization.name}}</a><br>
                    <a href="{% url 'events:event_detail' pk=review.event.pk %}">{{review.event.name}}</a><br>
                    {{review.rating}}<br>
                    {{review.review}}<br><br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/volunteer_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}Волонтер - {{user.get_full_name}}{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c d-flex">
                <div class="content-l">
                    <div class="content d-flex">
                        <img width="180" height="180" class="user-avatar" src="{{user.avatar.url}}">
                        <div class="profile-title">
                            <span class="profile-name">{{user.get_full_name}}</span>
                            <span class="profile-status">{{user.status}}</span>
                            {% if request.user.pk == user.pk %}
                                <a class="link-create mt-2" href="{% url 'users:edit' %}">Редактировать</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="profile-info">
                        <div class="profile-info-title">
                            <span>Личная информация</span>
                        </div>
                        <div class="profile-info-txt">
                            {% if user.info %}
                                {{user.info|safe}}
                            {% else %}
                                <span class="txt-empty">Личная информация отсутствует.</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="profile-info">
                        <div class="profile-info-title">
                            <span>Направления</span>
                        </div>
                        <div class="profile-info-txt">
                            {% if user.direction.all %}
                                {% for direction in user.direction.all %}
                                    <span>{{direction.name}}</span>
                                {% endfor %}
                            {% else %}
                                <span class="txt-empty">Направления отсутствуют.</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="profile-info">
                        <div class="profile-info-title">
                            <span>Мероприятия</span>
                        </div>
                        <div class="profile-info-txt">
                            {% if user.events_many.all %}
                                {% for event in user.events_many.all %}
                                    <a href="{% url 'events:event_detail' pk=event.pk %}">{{event.name}}</a><br>
                                    {{event.status}}<br>
                                    {{event.date_start}} - {{event.date_end}}<br>
                                {% endfor %}
                                {% if user.events_many.count > 3 %}
                                    <a href="{% url 'users:events' pk=user.pk %}">Смотреть все</a>
                                {% endif %}
                            {% else %}
                                <span class="txt-empty">Мероприятия отсутствуют.</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="profile-info">
                        <div class="profile-info-title">
                            <span>Отзывы</span>
                        </div>
                        <div class="profile-info-txt">
                            {% if user.reviews_user.all %}
                                {% for review in user.reviews_user.all %}
                                    <div class="profile-review">
                                        <a href="{% url 'projects:project_detail' pk=review.organization.pk %}">{{review.organization.name}}</a><br>
                                        <a href="{% url 'events:event_detail' pk=review.event.pk %}">{{review.event.name}}</a><br>
                                        {{review.rating}}<br>
                                        {{review.review}}<br><br>
                                    </div>
                                {% endfor %}
                                {% if user.reviews_user.count > 5 %}
                                    <a href="{% url 'users:reviews' pk=user.pk %}">Смотреть все</a>
                                {% endif %}
                            {% else %}
                                <span class="txt-empty">Отзывы отсутствуют.</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="content-r">
                    <div class="cr-r-title cr-r-title-stat">
                        <i class="fa-solid fa-ranking-star"></i>
                        <span>Статистика</span>
                    </div>
                    <div class="cr-r-info">
                        <span class="stat-num">{{stats_review}}</span>
                        <span class="stat-name">{% declension stats_review 'Отзыв' 'Отзыва' 'Отзывов' %}</span>
                        <span class="stat-num">{{stats_event}}</span>
                        <span class="stat-name">{% declension stats_event 'Мероприятие' 'Мероприятия' 'Мероприятий' %}</span>
                    </div>
                    <div class="cr-r-title">
                        <i class="fa-solid fa-ranking-star"></i>
                        <span>Рейтинг</span>
                    </div>
                    <div class="cr-r-info">
                        {% if rating %}
                            <div class="cr-r-stars">
                                <span>{{rating}}</span>
                                {% for x in 5|times%}
                                    {% if x|rating_counter:rating > 100 %}
                                        <i class="fa-solid fa-star star-s" style="background-image: linear-gradient(90deg, #ffe700 100%, #C7C7C7 0%);"></i>
                                    {% elif x|rating_counter:rating > 0 %}
                                        <i class="fa-solid fa-star star-s" style="background-image: linear-gradient(90deg, #ffe700 {{x|rating_counter:rating}}%, #C7C7C7 0%);"></i>
                                    {% else %}
                                        <i class="fa-solid fa-star star-s" style="background-image: linear-gradient(90deg, #ffe700 0%, #C7C7C7 100%);"></i>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="empty-container"><span class="txt-empty">Рейтинг отсутствует.</span></div>
                        {% endif %}
                    </div>
                    <div class="cr-r-title">
                        <i class="fa-solid fa-certificate"></i>
                        <span>Сертификаты</span>
                    </div>
                    <div class="cr-r-info">
                        {% if user.certificates.all %}
                            <div class="cr-r-content" id="modalCert">
                                {% for certificate in user.certificates.all %}
                                    <img height="50" width="80" src="{% static certificate.url %}" v-on:click="openModal('{% static certificate.url %}')">
                                {% endfor %}
                                <br><a href="{% url 'users:certificates' pk=user.pk %}">Смотреть все</a><br>
                                <div class="modalDialog" :key="isModal" v-if="isModal">
                                    <div>
                                        <img height="500" width="800" :src="src" v-on:click="openModal">
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="empty-container"><span class="txt-empty">Сертификаты отсутствуют.</span></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/volunteer.js' %}"></script>
{% endblock %}