events/urls.py
from django.urls import path, include

from events.views import EventsListActive, EventsListProcess, EventsListClose
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsList, name='event_list'),
    path('active/', EventsListActive.as_view(), name='EventsListActive'),
    path('process/', EventsListProcess.as_view(), name='EventsListProcess'),
    path('closed/', EventsListClose.as_view(), name='EventsListClose'),
    path('<int:pk>/', views.EventDetail, name='event_detail'),
    path('<int:pk>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('<int:pk>/unfavorite/', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite/', views.profile_favorite, name='profile_favorite'),
    path('<int:pk_event>/unfollow/<int:pk_funk>', views.profile_unfollow_func, name='profile_unfollow_func'),
    path('<int:pk_event>/follow/<int:pk_funk>', views.profile_follow_func, name='profile_follow_func'),
    path('follow/', views.follow_index, name='follow_index'),
    path('favorites/', views.favorites_index, name='favorites_index'),
    path('own/', views.own_index, name='own_index'),
    path('event_create/', views.event_create, name='event_create'),
    path('<int:pk>/function_create/', views.function_create, name='function_create'),
    path('<int:pk>/event_edit/', views.event_edit, name='event_edit'),
    path('<int:pk>/function_edit/', views.function_edit, name='function_edit'),

]

live/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from live.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('events/', include('events.urls', namespace='events')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', HomeView.as_view(), name='live_index'),
    path('auth/', include('auth_users.urls', namespace='auth_users')),
    path('volunteers/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import ProjectDetail, ProjectsList
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectsList.as_view(), name='projects_list'),
    path('<int:pk>/', views.ProjectDetail, name='project_detail'),
    path('<int:pk>/unfavorite', views.profile_unfavorite, name='profile_unfavorite'),
    path('<int:pk>/favorite', views.profile_favorite, name='profile_favorite'),
    path('<int:pk>/favorite_part', views.profile_favorite_part, name='profile_favorite_part'),

]

users/urls.py
from django.urls import path

from .views import UserListView, UserDetailView, EventListView, CertificateListView, ReviewListView, UserEdit

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(template_name='users/volunteers.html'), name='volunteers'),
    path('<int:pk>/', UserDetailView.as_view(template_name='users/volunteer_detail.html'), name='volunteer_detail'),
    path('<int:pk>/events/', EventListView.as_view(template_name='users/events.html'), name='events'),
    path('<int:pk>/certificates/', CertificateListView.as_view(template_name='users/certificates.html'), name='certificates'),
    path('<int:pk>/reviews/', ReviewListView.as_view(template_name='users/reviews.html'), name='reviews'),
    path('edit/', UserEdit.as_view(template_name='users/edit.html'), name='edit'),
]

events/forms.py
from django.forms import ModelForm, DateField, modelformset_factory
from django import forms
from .models import Follow, Function, Event
from datetime import datetime
from django.forms.widgets import ClearableFileInput, DateTimeInput


class EventForm(ModelForm):
    class Meta:
        model = Follow
        fields = ('function',)

    def __init__(self, *args, **kwargs):
        if 'event' in kwargs and kwargs['event'] is not None:
            event = kwargs.pop('event')
            qs = Function.objects.filter(event_id=event.pk)
            total_pk = []
            for qs_one in qs:
                if qs_one.count > qs_one.following.count():
                    total_pk.append(qs_one.pk)
            qs = qs.filter(pk__in=total_pk)
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['function'].queryset = qs


class EventInput(ClearableFileInput):
    template_name = "includes/event_input.html"


class EventFormCreate(ModelForm):
    date_start = forms.DateTimeField(
        label='Дата начала')

    date_end = forms.DateTimeField(
        label='Дата окончания')

    class Meta:
        model = Event
        fields = ('coordinates_latitude', 'coordinates_longitude', 'address', 'avatar_url', 'name', 'status', 'description', 'date_start', 'date_end', 'project')
        widgets = {
            'avatar_url': EventInput
        }


class FunctionFormCreate(ModelForm):
    class Meta:
        model = Function
        fields = ('name', 'description', 'task', 'condition', 'count')

events/views.py
import json

from django.views.generic import DetailView, ListView
from django.shortcuts import redirect, get_object_or_404, render, reverse
from datetime import datetime

from .models import Event, Follow, Function, Favorites
from .filters import Event_Filter
from .forms import EventForm, EventFormCreate, FunctionFormCreate
from django.contrib.auth.decorators import login_required

from rest_framework import serializers
from rest_framework.renderers import JSONRenderer

from events.models import Event
from users.models import User
from projects.models import Project


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('pk', 'avatar', 'first_name', 'last_name')


class ProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = ('pk', 'name', 'marker')


class EventSerializer(serializers.ModelSerializer):
    contact_user = UserSerializer(read_only=True)
    project = ProjectSerializer(read_only=True)

    class Meta:
        model = Event
        fields = ('pk', 'name', 'date_end', 'date_start', 'coordinates_latitude', 'coordinates_longitude', 'address', 'project', 'contact_user')


@login_required
def EventDetail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    following = Follow.objects.filter(user=request.user, event=event).exists()
    favorites = Favorites.objects.filter(user=request.user, event=event).exists()
    following_func = []
    for i in Follow.objects.filter(user=request.user, event=event):
        following_func.append(i.function.pk)
    functions = Function.objects.filter(event=event)
    len_functions = len(functions)
    user_count = event.following.count()
    users_following = Follow.objects.filter(event=event)
    count_u=[]
    for i in functions:
        count_u.append(int(i.count))
    count_remainder = (True if (sum(count_u)>user_count) else False)
    count_u_func={}
    for i in functions:
        count_u_func[i.pk] = i.following.count()
    form = EventForm(request.POST or None, event=event)
    if form.is_valid():
        fun = form.save(commit=False)
        fun.user = request.user
        fun.event = event
        fun.save()
        return redirect('events:event_detail', pk=pk)
    context = {
        'event': event,
        'following': following,
        'functions': functions,
        'user_count': user_count,
        'favorites': favorites,
        'users_following': users_following,
        'len_functions': len_functions,
        'count_remainder': count_remainder,
        'following_func': following_func,
        'count_u_func': count_u_func,
        'form': form
    }
    return render(request, 'events/event_detail.html', context)


def EventsList(request):
    events = Event.objects.all()
    filter = Event_Filter(request.GET, queryset=events)
    events = filter.qs
    context = {'events': events, 'filter': filter}
    return render(request, 'events/events.html', context)


class EventsListActive(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            functions=Function.objects.filter(event=event_one)
            count_u = []
            for i in functions:
                count_u.append(int(i.count))
            if sum(count_u)>event_one.following.count() and event_one.date_end.date()>datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


class EventsListProcess(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            functions=Function.objects.filter(event=event_one)
            count_u = []
            for i in functions:
                count_u.append(int(i.count))
            if sum(count_u)==event_one.following.count() and event_one.date_end.date()>datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


class EventsListClose(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events_all=Event.objects.all()
        events_pk=[]
        for event_one in events_all:
            if event_one.date_end.date()<datetime.now().date():
                events_pk.append(event_one.pk)
        events=events_all.filter(pk__in=events_pk)
        filter = Event_Filter(self.request.GET, queryset=events)
        events = filter.qs
        context['events'] = events
        context['filter'] = filter
        return context


@login_required
def profile_unfollow(request, pk):
    follow = get_object_or_404(Event, pk=pk)
    Follow.objects.filter(user=request.user, event=follow).delete()
    return redirect('events:event_detail', pk=pk)


@login_required
def follow_index(request):
    follows = Event.objects.filter(following__user=request.user)
    serializer = EventSerializer(follows, many=True)
    context = {
        'follows': follows,
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'condition': True
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def profile_unfavorite(request, pk):
    favorite = get_object_or_404(Event, pk=pk)
    Favorites.objects.filter(user=request.user, event=favorite).delete()
    return redirect('events:event_detail', pk=pk)


@login_required
def profile_favorite(request, pk):
    favorite = get_object_or_404(Event, pk=pk)
    Favorites.objects.get_or_create(user=request.user, event=favorite)
    return redirect('events:event_detail', pk=pk)


@login_required
def profile_unfollow_func(request, pk_event, pk_funk):
    event_follow = get_object_or_404(Event, pk=pk_event)
    func_follow = get_object_or_404(Function, event_id=event_follow.pk, pk=pk_funk)
    Follow.objects.filter(user=request.user, event=event_follow, function=func_follow).delete()
    return redirect('events:event_detail', pk=event_follow.pk)

@login_required
def profile_follow_func(request, pk_event, pk_funk):
    event_follow = get_object_or_404(Event, pk=pk_event)
    func_follow = get_object_or_404(Function, event_id=event_follow.pk,pk=pk_funk)
    Follow.objects.get_or_create(user=request.user, event=event_follow, function=func_follow)
    return redirect('events:event_detail', pk=event_follow.pk)


@login_required
def favorites_index(request):
    favorites = Event.objects.filter(favorites__user=request.user)
    serializer = EventSerializer(favorites, many=True)
    context = {
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'follows': favorites,
        'condition': True
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def own_index(request):
    owns = Event.objects.filter(contact_user=request.user)
    serializer = EventSerializer(owns, many=True)
    context = {
        'owns': owns,
        'events_json': json.loads(JSONRenderer().render(serializer.data)),
        'condition': False
    }
    return render(request, 'events/events_follow.html', context)


@login_required
def event_create(request):
    form = EventFormCreate(request.POST or None)
    if form.is_valid():
        event = form.save(commit=False)
        event.contact_user = request.user
        event.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_event.html', {'form': form}
    )


@login_required
def function_create(request, pk):
    form = FunctionFormCreate(request.POST or None)
    event = Event.objects.get(pk=pk)
    if form.is_valid():
        function = form.save(commit=False)
        function.event = event
        function.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_function.html', {'form': form}
    )


@login_required
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.user != event.contact_user:
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    form = EventFormCreate(
        request.POST or None,
        files=request.FILES or None,
        instance=event
    )
    if form.is_valid():
        form.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': event.pk}
        ))
    return render(
        request, 'events/create_event.html', {'form': form}
    )


@login_required
def function_edit(request, pk):
    function = get_object_or_404(Function, pk=pk)
    if request.user != function.event.contact_user:
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': function.event.pk}
        ))
    form = FunctionFormCreate(
        request.POST or None,
        files=request.FILES or None,
        instance=function
    )
    if form.is_valid():
        form.save()
        return redirect(reverse(
            'events:event_detail', kwargs={'pk': function.event.pk}
        ))
    return render(
        request, 'events/create_function.html', {'form': form}
    )

templates/events/create_event.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}

{% block title %}Форма{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c">
                <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
                    {% csrf_token %}
                    {{ form.media }}
                    {% for field in form %}
                        {% if field.label == 'Аватар мероприятия'%}
                            {{field}}
                        {% else %}
                            <div class="mt-4 d-flex">
                                <span class="form-edit-label">{{ field.label }}</span>
                                <div>
                                    {% if field.label == 'Описание события' %}
                                        <div class="form-edit-info-container">
                                            <div class="form-edit-info-nav">
                                                <span id="form-edit-info-b" class="blr-24"><i class="fa-solid fa-bold"></i></span>
                                                <span id="form-edit-info-p"><i class="fa-solid fa-paragraph"></i></span>
                                            </div>
                                            {{field}}
                                        </div>
                                    {% else %}
                                        {{field|add_class:'form-edit-user'}}
                                    {% endif %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <span class="form-edit-error">* {{ error|escape }}</span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <button class="btn-save" type="submit">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/event_create.js' %}"></script>
    <script src="{% static 'js/datetimepicker.js' %}"></script>
{% endblock %}

templates/events/create_function.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}Создать функцию{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div class="content-c">
                    <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
                        {% csrf_token %}
                          {% for field in form %}
                            <div class="mt-4 d-flex">
                                <span class="form-edit-label">{{ field.label }}</span>
                                    <div>
                                        {% if field.label == 'Описание' %}
                                            <div class="form-edit-info-container">
                                                <div class="form-edit-info-nav">
                                                    <span id="form-edit-info-b1" class="blr-24"><i class="fa-solid fa-bold"></i></span>
                                                    <span id="form-edit-info-p1"><i class="fa-solid fa-paragraph"></i></span>
                                                </div>
                                                {{field}}
                                            </div>
                                        {% elif field.label == 'Задачи' %}
                                            <div class="form-edit-info-container">
                                                <div class="form-edit-info-nav">
                                                    <span id="form-edit-info-b2" class="blr-24"><i class="fa-solid fa-bold"></i></span>
                                                    <span id="form-edit-info-p2"><i class="fa-solid fa-paragraph"></i></span>
                                                </div>
                                                {{field}}
                                            </div>
                                        {% elif field.label == 'Условия' %}
                                            <div class="form-edit-info-container">
                                                <div class="form-edit-info-nav">
                                                    <span id="form-edit-info-b3" class="blr-24"><i class="fa-solid fa-bold"></i></span>
                                                    <span id="form-edit-info-p3"><i class="fa-solid fa-paragraph"></i></span>
                                                </div>
                                                {{field}}
                                            </div>
                                        {% else %}
                                        {{field|add_class:'form-edit-user'}}
                                        {% endif %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <span class="form-edit-error">* {{ error|escape }}</span>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                            </div>
                          {% endfor %}
                            <button class="btn-save" type="submit">
                                Сохранить
                            </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/function_create.js' %}"></script>
{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load static %}
{% block title %}Живи{% endblock %}
{% block content %}
<div class="limiter cl-gr">
      <div class="container-fix">
            <div class="content-c d-flex">
                <div class="content-l">
                      <div class="content d-flex">
                           <img width="180" height="180" src="{{ event.avatar_url.url }}">
                           <div class="event-title">
                                 <span class="event-name">{{ event.name }}</span>
                                 {% if request.user == event.contact_user %}
                                    <a class="link-create mt-2" href="{% url 'events:event_edit' pk=event.pk %}">Редактировать</a>
                                 {% endif %}
                           </div>
                    </div>
                    <div class="event-info">
                        <div class="event-info-title">
                            <span>Основная информация</span>
                        </div>
                        <div class="event-info-txt">
                              <ul>
                                    <li>
                                         <a href="{% url 'projects:project_detail' pk=event.project.pk %}">{{ event.project }}</a>
                                    </li>
                                    <li>
                                         {{ event.status }}
                                    </li>
                                    <li>
                                          {{ event.date_start }} - {{ event.date_end }}
                                    </li>
                              </ul>
                        </div>
                    </div>
                    <div class="event-info">
                        <div class="event-info-title">
                            <span>Описание</span>
                        </div>
                        <div class="event-info-txt">
                              <span>{{ event.description|safe }}</span>
                        </div>
                    </div>
                </div>
                <div class="content-r">
                    <div class="cr-r-info">
                        {% if favorites %}
                            <a class="link-favorite" href="{% url 'events:profile_unfavorite' pk=event.pk %}">
                                <i class="fa-solid fa-star"></i><span>Из избранного</span>
                            </a>
                        {% else %}
                            <a class="link-favorite" href="{% url 'events:profile_favorite' pk=event.pk %}">
                                <i class="fa-regular fa-star"></i><span>В избранное</span>
                            </a>
                        {% endif %}
                    </div>
                    <div class="cr-r-title">
                        <i class="fa-solid fa-ranking-star"></i>
                        <span>Контактное лицо</span>
                    </div>
                    <div class="cr-r-info">
                        <a class="map-user-link" href="{% url 'users:volunteer_detail' pk=event.contact_user.pk%}">
                              <div class="content-user-menu mb-1">
                                    <img width="40" height="40" class="content-user-avatar" src="{{event.contact_user.avatar.url}}">
                                    <span class="content-user-name">{{event.contact_user.get_full_name}}</span>
                              </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="content-f">
                <div class="event-info-title">
                    <span>Функции</span>
                    {% if request.user == event.contact_user %}
                        <a class="link-create ms-4" href="{% url 'events:function_create' pk=event.pk %}">
                              Добавить
                        </a>
                    {% endif%}
                </div>
                {% for function in functions %}
                    <div class="funct-content d-flex">
                        <div class="func-l text-center">
                            <span class="func-l-name mb-4 inglobal-bold">{{ function.name }}</span>
                            <span class="func-l-cnt mb-4 inglobal-bold">{{ function.following.count }} из {{ function.count }}</span>
                            <div class="mb-4">
                                {% for user_following in function.following.all %}
                                    <a href="{% url 'users:volunteer_detail' pk=user_following.user.pk%}">
                                        <img width="40" height="40" class="content-user-avatar me-2" src="{{user_following.user.avatar.url}}"></a>
                                {% endfor %}
                            </div>
                            <div>
                                {% if request.user == event.contact_user %}
                                    <a class="link-create" href="{% url 'events:function_edit' pk=function.pk %}">
                                         Редактировать
                                    </a>
                                {% else %}
                                    {% if function.pk in following_func %}
                                        <a class="link-create" href="{% url 'events:profile_unfollow_func' pk_event=event.pk pk_funk=function.pk %}">
                                            Выйти
                                        </a>
                                    {% else %}
                                        {% if following %}
                                            Вы присоединились к другой функции
                                        {% else%}
                                            {% if count_u_func|get_item:function.pk < function.count %}
                                                <a class="link-create" href="{% url 'events:profile_follow_func' pk_event=event.pk pk_funk=function.pk %}">
                                                   Присоединиться
                                                </a>
                                            {% else %}
                                                Волонтеры наброны
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endif%}
                            </div>
                        </div>
                        <div class="func-r">
                            <div>
                                <h4 class="func-r-name">Описание:</h4>
                                <p>{{ function.description|safe }}</p>
                                <h4 class="func-r-name">Задачи:</h4>
                                <p>{{ function.task|safe }}</p>
                                <h4 class="func-r-name">Условия:</h4>
                                <p>{{ function.task|safe }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
      </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/event.js' %}"></script>
{% endblock %}

templates/events/events.html
{% extends "base.html" %}
{% load static %}
{% block title %}Мероприятия{% endblock %}
{% block content %}
<div class="limiter">
      <div class="container-fix">
          {% include 'includes/switcher_status_events.html' %}
          <div class="container-fix d-flex">
              <div class="content-l">
                    <div class="line_block">
                        {% for event in events %}
                            <a href="{% url 'events:event_detail' pk=event.pk %}">
                                <div class="line_block_items">
                                    <img src="{{ event.avatar_url.url }}"> <br>
                                    <p class="title_line_block">{{ event.name }}</p>
                                    <p class="hideText">{{ event.status }}
                                    <br>{{ event.date_start|date:"d E Y" }} -  {{ event.date_end|date:"d E Y" }}</p>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
              </div>
              <div class="content-r">
                <form method="get">
                    <div>
                      {{ filter.form }}
                    </div>
                  <button class="btn-save" type="submit"> Поиск </button>
                </form>
              </div>
          </div>
      </div>
</div>
{% endblock %}

templates/events/events_follow.html
{% extends "base.html" %}
{% load static %}
{% block title %}Мероприятия{% endblock %}
{% block content %}
<div class="limiter">
      <div class="container-fix">
          {% include 'includes/switcher.html' %}
          {% if condition %}
                <div class="content-map">
                    <div id="map" style="width: 100%; height: 700px" :onchange="loadMap({{events_json}})"></div>
                </div>
          {% else %}
                <div class="content-map">
                    <div id="map" style="width: 100%; height: 700px" :onchange="loadMap({{events_json}})"></div>
                </div>
          {% endif %}
      </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/yandex_map.js' %}"></script>
{% endblock %}

templates/events/follow.html
{% extends "base.html" %}
{% load static %}
{% block title %}Форма{% endblock %}
{% block content %}
    <div class="limiter cl-gr">
        <div class="container-fix">
            <div>
                <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
                    {% csrf_token %}
                      {% for field in form %}
                            <label>
                                {{ field }}
                            </label>
                          {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help">
                              {{ field.help_text|safe }}
                            </small>
                          {% endif %}
                      {% endfor %}
                        <button class="btn-save" type="submit">
                            Сохранить
                        </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}